spring:
  application:
    name: cloud-doc-manager
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/clouddoc_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:Kunal123}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
